[package]
name = "aster-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "1.3"
spin = "0.9.4"
ostd = { path = "../../../ostd" }
aster-util = { path = "../../libs/aster-util" }
component = { path = "../../libs/comp-sys/component" }
log = "0.4"